### ISSUE TITLE
Add MicroPub option to Sharing dialog

### ISSUE THREAD

**Issue by michielbdejong** [Decentralized-Sharing-Working-Group/cozy-photos#1]

**Comment by michielbdejong** [comment]
Hm, looks like maybe that dialog is part of cozy-clearance, not cozy-photos.

![cozy-photo-sharing](https://cloud.githubusercontent.com/assets/408412/8058115/5921bf78-0eb7-11e5-9b2b-ad5e9de35ce1.png)

**Comment by michielbdejong** [comment]
I made [some changes in cozy-clearance](https://github.com/Decentralized-Sharing-Working-Group/cozy-clearance/issues/1#issue-86907632) and I'm now trying to make those show up.

Inside my cozy/full container with the photos app installed, I'm running:

``` bash
cd /usr/local/apps/photos
cd client
npm install -g brunch
npm install javascript-brunch
npm install css-brunch
npm install coffee-script-brunch
npm install stylus-brunch
npm install jade-brunch
npm install digest-brunch
npm install clean-css-brunch
brunch build
```

But this seems to succeed even with `/usr/local/cozy/apps/photos/node_modules/cozy-clearance` removed.

**Comment by michielbdejong** [comment]
@Gara64 Do you know how these build steps should work for the photos app?

**Comment by michielbdejong** [comment]
The 'Share with Micropub' button should do two things:
- obtain an access_token via IndieAuth token service, see http://indiewebcamp.com/token-endpoint
- use this access_token to POST from Cozy to Known (or to any other MicroPub-enabled blogging software), see http://indiewebcamp.com/micropub#Syntax

I'm not sure whether I'm the right person to work on this, given my very limited knowledge of developing with brunch. Instead of me learning how to do this, maybe someone wants to jump in who is already up to speed with the brunch methodology? @Gara64 What are your thoughts on this?

**Comment by aenario** [comment]
Hi @michielbdejong ,

After making changes to cozy-clearance client, 

``` bash
cd /cozy-clearance && coffeegulp
cp /cozy-clearance/client/build.js /cozy-photos/client/vendor/scripts/clearance.js
```

This does need more documentation in cozy-clearance :-)

**Comment by m4dz** [comment]
Hi @michielbdejong :)

On cozy apps, we've got two parts: the server one, located at root in the repo (the `server.coffee` file and the `server` directory) ; and the client (front-end) part, located in the `client` directory.

If you want to work on the client part, you must go into the client folder, and run:

``` sh
$ npm -g i brunch    # first time only, to install the brunch runner globaly
$ npm i    # to install the dependencies listed in the `client/package.json` file
```

Concerning the clearance module which is responsible of the sharing part, there is a server-side component (listed as a dependency in the `/package.json` file for the server) and the frontend client library (the `/client/vendor/scripts/clearance.js` file). When you compile the client part with `brunch b` (or `brunch w`), the clearance frontend lib is embedded to the `vendors.js` file.

So, if I understand correctly your issue, you:
1. need to update the code in the cozy-clearance codebase to add MicroPub option sharing dialog
2. Update the frontend script in the vendor directory
3. Update (if needed) the server-part of cozy-clearance 
4. Test your build :)

Does it sounds ok to you (or do I missunderstand completely your problem?)

**Comment by michielbdejong** [comment]
@aenario ok, that helps a lot, but coffeegulp is not creating `client/build.js`, it seems:

``` bash
root@62cea0833a47:/usr/local/cozy/apps/photos/node_modules/cozy-clearance-new# npm install -g coffeegulp
/usr/local/bin/coffeegulp -> /usr/local/lib/node_modules/coffeegulp/index.js
coffeegulp@0.0.7 /usr/local/lib/node_modules/coffeegulp
├── coffee-script@1.9.3
└── gulp@3.9.0 (pretty-hrtime@1.0.0, interpret@0.6.2, deprecated@0.0.1, archy@1.0.0, tildify@1.0.0, v8flags@2.0.5, minimist@1.1.1, semver@4.3.6, orchestrator@0.3.7, chalk@1.0.0, gulp-util@3.0.5, liftoff@2.1.0, vinyl-fs@0.3.13)
root@62cea0833a47:/usr/local/cozy/apps/photos/node_modules/cozy-clearance-new# coffeegulp               
[08:35:41] Using gulpfile /usr/local/cozy/apps/photos/node_modules/cozy-clearance-new/gulpfile.coffee
[08:35:41] Starting 'buildclient'...
[08:35:41] Finished 'buildclient' after 722 ms
[08:35:41] Starting 'default'...
[08:35:41] Finished 'default' after 29 μs
root@62cea0833a47:/usr/local/cozy/apps/photos/node_modules/cozy-clearance-new# ls client     
contact_autocomplete.coffee  contact_collection.coffee  modal.coffee  modal_share_template.jade  modal_share_view.coffee
```

**Comment by aenario** [comment]
My bad, it was /cozy-clearance/client-build.js

**Comment by michielbdejong** [comment]
@m4dz Ah ok, there is a package.json inside the client/ folder, that's the bit I missed, that's why I ended up adding the dependencies one by one.

OK, so I have updated /usr/local/cozy/apps/photos/client/vendor/scripts/clearance.js now, but now the `brunch b` step fails:

``` bash
root@62cea0833a47:/usr/local/cozy/apps/photos# brunch b

Error: couldn't load config /usr/local/cozy/apps/photos/config. Error: Cannot find module '/usr/local/cozy/apps/photos/config'
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:585:13)
  at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:583:22)
  at initialize (/usr/local/lib/node_modules/brunch/lib/watch.js:460:18)
  at new BrunchWatcher (/usr/local/lib/node_modules/brunch/lib/watch.js:649:5)
  at module.exports.watch (/usr/local/lib/node_modules/brunch/lib/watch.js:708:10)
  at start (/usr/local/lib/node_modules/brunch/lib/index.js:15:31)
  at Command.listener (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:289:8)
  at Command.EventEmitter.emit (events.js:98:17)
  at Command.parseArgs (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:572:12)
  at Command.parse (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:438:21)
  at Object.exports.run (/usr/local/lib/node_modules/brunch/lib/cli.js:63:11)
  at Object.<anonymous> (/usr/local/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

**Comment by aenario** [comment]
brunch b needs to be run from /usr/local/cozy/apps/photos/**client**

**Comment by michielbdejong** [comment]
aaaah ok :)

**Comment by michielbdejong** [comment]
ok, that looks better:

``` bash
root@62cea0833a47:/usr/local/cozy/apps/photos/client# brunch b  
/usr/local/cozy/apps/photos/build/client/public
12 Jun 08:56:46 - info: compiled 45 files into 4 files, copied 55 in 3245ms
```

After `docker restart` I see I successfully broke the photos app, it now only says 'Cannot GET /', so at least that means something happened. :)

I'm not sure how much more time I have to continue developing this, but at least I'm glad I was able to go through the whole build process successfully thanks to your help. Thanks a lot!

**Comment by paultranvan** [comment]
Sorry for the delay @michielbdejong, I was busy with a conference. 
I'm not a brunch ninja either, but I don't think this should be blocking, as the Cozy experts are here :)
Would you like to discuss about it on irc ?

**Comment by michielbdejong** [comment]
@Gara64 I think it's easiest to pass this part of the work over to the Cozy experts? The MicroPub syntax is described in http://indiewebcamp.com/micropub#Syntax so there's not much I can add to that from my side. Let's discuss on irc how we proceed from here!
